site_name: Study Notes
site_author: Rob Gillen
site_description: Digital scrapbook of various topics
theme:
  name: material
  features:
    - search.highlight

repo_url: https://github.com/argodev/study
edit_uri: ""

theme:
  name: material
  language: en
  palette:
    primary: grey
    accent: indigo
  font:
    text: Roboto Regular
    code: Roboto Mono

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/argodev
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/argodev 


use_directory_urls: false

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
    #   custom_fences:
    #     - name: mermaid
    #       class: mermaid-xperimental
    #       format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


plugins:
  - search
  - git-revision-date-localized:
      type: iso_datetime
      fallback_to_build_date: true

nav:
    - 'Overview': 'index.md'
    - 'Core Skills':
        - 'Assembly':
            - 'PowerPC': 'skills/assembly/ppc.md'
        - 'Languages':
            - 'C++': 'skills/languages/cpp.md'
        - 'Password Cracking':
            - 'Overview': 'skills/passwords/index.md'
            - 'Search Space': 'skills/passwords/searchspace.md'
            - 'HashCat': 'skills/passwords/hashcat.md'
            - 'John the Ripper': 'skills/passwords/john.md'
        - 'Reverse Engineering':
            - 'Ghidra': 'skills/re/ghidra.md'
            - 'Virtual Functions': 'skills/re/virtual_funcs.md'
        - 'Website Exploitation': 'skills/webexploit.md'
    - 'Capture The Flag (CTF)':
        - 'Hack The Box (HTB)': 'ctf/htb.md'
    - 'RingZer0 Team Online CTF': 
        - 'Overview': 'ctf/rzeroctf.md'
        - 'Coding Challenges': 'ctf/rz-coding.md'
        - 'Exotic Data Storage': 'ctf/rz-xdata.md'
        - 'Jail Escapes': 'ctf/rz-jailescape.md'
        - 'Javascript': 'ctf/rz-javascript.md'
    - 'PortSwigger Academy':
        - 'Overview': 'ctf/portswigger.md'
        - 'Access Control': 'ctf/ps-accesscontrol.md'
        - 'Cross-Site Scripting': 'ctf/ps-xss.md'
        - 'OS Command Injection': 'ctf/ps-oscmdi.md'
        - 'SQL Injection': 'ctf/ps-sqi.md'
        - 'Cross-Site Request Forgery': 'ctf/ps-csrf.md'
        - 'Directory Traversal': 'ctf/ps-dirtrav.md'
        - 'HTTP Host Headers': 'ctf/ps-hostheader.md'
    - 'PicoCTF':
        - 'Overview': 'ctf/picoCTF.md'
        - 'General Skills': 'ctf/pico-general.md'
        - 'Web Exploitation': 'ctf/pico-webex.md'
        - 'Binary Exploitation': 'ctf/pico-binex.md'
        - 'Cryptography': 'ctf/pico-crypto.md'
        - 'Forensics': 'ctf/pico-forensics.md'
        - 'Reverse Engineering': 'ctf/pico-re.md'
        - '2019 Competition': 'ctf/pico-2019.md'
#    - 'Linux':
#        - 'Linux From Scratch': 'linux/lfs.md'
#    - 'Test Beds': 
#        - 'Portable Testbed': 'testbed/index.md'
#        - 'Lan Turtle': 'testbed/lanturtle.md'
#        - 'Packet Squirrel': 'testbed/pktsquirrel.md'
#        - 'Virtual Machine Hosting': 'testbed/virtual_machines.md'
#        - 'VPN': 'testbed/vpn.md'
#    - 'Miscellany':
#        - 'Change Log': changelog.md
#        - 'License': license.md

copyright: Copyright &copy; 2021-2022 Rob Gillen

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - javascripts/tex-mml-chtml.js
  - javascripts/mermaid.min.js
